[
  {
    "create_table_sql": "-- ================================================\n-- TABELA: cashier_closing\n-- ================================================\nDROP TABLE IF EXISTS public.cashier_closing CASCADE;\nCREATE TABLE public.cashier_closing (\n    id BIGINT NOT NULL DEFAULT nextval('cashier_closing_id_seq'::regclass),\n    closing_date DATE NOT NULL,\n    start_time TIMESTAMPTZ,\n    end_time TIMESTAMPTZ,\n    total_sales NUMERIC(10, 2) DEFAULT 0,\n    total_discounts NUMERIC(10, 2) DEFAULT 0,\n    total_cancellations NUMERIC(10, 2) DEFAULT 0,\n    total_cash NUMERIC(10, 2) DEFAULT 0,\n    total_card NUMERIC(10, 2) DEFAULT 0,\n    total_pix NUMERIC(10, 2) DEFAULT 0,\n    expected_total NUMERIC(10, 2) DEFAULT 0,\n    declared_total NUMERIC(10, 2) DEFAULT 0,\n    difference NUMERIC(10, 2) DEFAULT 0,\n    notes TEXT,\n    closed_by UUID,\n    closed_at TIMESTAMPTZ DEFAULT now(),\n    status VARCHAR(20) DEFAULT 'closed'::character varying,\n    details JSONB,\n    created_at TIMESTAMPTZ DEFAULT now()\n);\n\n"
  },
  {
    "create_table_sql": "-- ================================================\n-- TABELA: companies\n-- ================================================\nDROP TABLE IF EXISTS public.companies CASCADE;\nCREATE TABLE public.companies (\n    id UUID NOT NULL DEFAULT gen_random_uuid(),\n    name VARCHAR(255) NOT NULL,\n    slug VARCHAR(100) NOT NULL,\n    domain VARCHAR(255),\n    settings JSONB DEFAULT '{}'::jsonb,\n    status VARCHAR(20) DEFAULT 'active'::character varying,\n    created_at TIMESTAMP DEFAULT now(),\n    updated_at TIMESTAMP DEFAULT now()\n);\n\n"
  },
  {
    "create_table_sql": "-- ================================================\n-- TABELA: company_settings\n-- ================================================\nDROP TABLE IF EXISTS public.company_settings CASCADE;\nCREATE TABLE public.company_settings (\n    id UUID NOT NULL DEFAULT gen_random_uuid(),\n    company_name VARCHAR(255) NOT NULL,\n    company_logo TEXT,\n    company_logo_url TEXT,\n    favicon TEXT,\n    domain VARCHAR(255),\n    email VARCHAR(255),\n    phone VARCHAR(50),\n    address TEXT,\n    city VARCHAR(100),\n    state VARCHAR(50),\n    zip_code VARCHAR(20),\n    cnpj VARCHAR(20),\n    social_media JSONB DEFAULT '{}'::jsonb,\n    primary_color VARCHAR(7) DEFAULT '#2563eb'::character varying,\n    secondary_color VARCHAR(7) DEFAULT '#7c3aed'::character varying,\n    custom_css TEXT,\n    created_at TIMESTAMP DEFAULT now(),\n    updated_at TIMESTAMP DEFAULT now()\n);\n\n"
  },
  {
    "create_table_sql": "-- ================================================\n-- TABELA: coupon_allowed_customers\n-- ================================================\nDROP TABLE IF EXISTS public.coupon_allowed_customers CASCADE;\nCREATE TABLE public.coupon_allowed_customers (\n    id BIGINT NOT NULL DEFAULT nextval('coupon_allowed_customers_id_seq'::regclass),\n    coupon_id BIGINT,\n    customer_id BIGINT,\n    created_at TIMESTAMPTZ DEFAULT now()\n);\n\n"
  },
  {
    "create_table_sql": "-- ================================================\n-- TABELA: coupons\n-- ================================================\nDROP TABLE IF EXISTS public.coupons CASCADE;\nCREATE TABLE public.coupons (\n    id BIGINT NOT NULL DEFAULT nextval('coupons_id_seq'::regclass),\n    code VARCHAR(50) NOT NULL,\n    name VARCHAR(255) NOT NULL,\n    description TEXT,\n    discount_type VARCHAR(20) NOT NULL,\n    discount_value NUMERIC(10, 2) NOT NULL,\n    max_discount NUMERIC(10, 2),\n    min_purchase NUMERIC(10, 2) DEFAULT 0,\n    is_global BOOLEAN DEFAULT true,\n    is_active BOOLEAN DEFAULT true,\n    valid_from TIMESTAMPTZ,\n    valid_to TIMESTAMPTZ,\n    usage_limit INTEGER,\n    used_count INTEGER DEFAULT 0,\n    created_at TIMESTAMPTZ DEFAULT now(),\n    created_by UUID,\n    updated_at TIMESTAMPTZ DEFAULT now(),\n    updated_by UUID\n);\n\n"
  },
  {
    "create_table_sql": "-- ================================================\n-- TABELA: customer_communications\n-- ================================================\nDROP TABLE IF EXISTS public.customer_communications CASCADE;\nCREATE TABLE public.customer_communications (\n    id UUID NOT NULL DEFAULT gen_random_uuid(),\n    customer_id BIGINT NOT NULL,\n    channel VARCHAR(20) NOT NULL,\n    subject TEXT,\n    content TEXT NOT NULL,\n    status VARCHAR(20) DEFAULT 'sent'::character varying,\n    sent_by UUID,\n    created_at TIMESTAMPTZ DEFAULT now(),\n    updated_at TIMESTAMPTZ DEFAULT now()\n);\n\n"
  },
  {
    "create_table_sql": "-- ================================================\n-- TABELA: customer_coupons\n-- ================================================\nDROP TABLE IF EXISTS public.customer_coupons CASCADE;\nCREATE TABLE public.customer_coupons (\n    id BIGINT NOT NULL DEFAULT nextval('customer_coupons_id_seq'::regclass),\n    coupon_id BIGINT,\n    customer_id BIGINT,\n    sale_id BIGINT,\n    used_at TIMESTAMPTZ DEFAULT now()\n);\n\n"
  },
  {
    "create_table_sql": "-- ================================================\n-- TABELA: customers\n-- ================================================\nDROP TABLE IF EXISTS public.customers CASCADE;\nCREATE TABLE public.customers (\n    id BIGINT NOT NULL DEFAULT nextval('customers_id_seq'::regclass),\n    name VARCHAR(255) NOT NULL,\n    email VARCHAR(255) NOT NULL,\n    phone VARCHAR(20) NOT NULL,\n    document VARCHAR(18),\n    address VARCHAR(255),\n    city VARCHAR(100),\n    state VARCHAR(2),\n    zip_code VARCHAR(10),\n    birth_date DATE,\n    status VARCHAR(20) DEFAULT 'active'::character varying,\n    total_purchases NUMERIC(10, 2) DEFAULT 0,\n    last_purchase DATE,\n    created_at TIMESTAMPTZ DEFAULT now(),\n    updated_at TIMESTAMPTZ DEFAULT now()\n);\n\n"
  },
  {
    "create_table_sql": "-- ================================================\n-- TABELA: login_attempts\n-- ================================================\nDROP TABLE IF EXISTS public.login_attempts CASCADE;\nCREATE TABLE public.login_attempts (\n    id UUID NOT NULL DEFAULT gen_random_uuid(),\n    email VARCHAR(255) NOT NULL,\n    ip_address VARCHAR(45),\n    user_agent TEXT,\n    attempts INTEGER DEFAULT 0,\n    is_blocked BOOLEAN DEFAULT false,\n    blocked_until TIMESTAMPTZ,\n    last_attempt TIMESTAMPTZ DEFAULT now(),\n    unlocked_by UUID,\n    unlocked_at TIMESTAMPTZ,\n    created_at TIMESTAMPTZ DEFAULT now(),\n    updated_at TIMESTAMPTZ DEFAULT now()\n);\n\n"
  },
  {
    "create_table_sql": "-- ================================================\n-- TABELA: notifications\n-- ================================================\nDROP TABLE IF EXISTS public.notifications CASCADE;\nCREATE TABLE public.notifications (\n    id UUID NOT NULL DEFAULT gen_random_uuid(),\n    user_id UUID,\n    title VARCHAR(255) NOT NULL,\n    message TEXT NOT NULL,\n    type VARCHAR(50) DEFAULT 'info'::character varying,\n    read BOOLEAN DEFAULT false,\n    read_at TIMESTAMPTZ,\n    link TEXT,\n    entity_id TEXT,\n    entity_type VARCHAR(100),\n    created_at TIMESTAMPTZ DEFAULT now(),\n    updated_at TIMESTAMPTZ DEFAULT now()\n);\n\n"
  },
  {
    "create_table_sql": "-- ================================================\n-- TABELA: permissions\n-- ================================================\nDROP TABLE IF EXISTS public.permissions CASCADE;\nCREATE TABLE public.permissions (\n    id INTEGER NOT NULL DEFAULT nextval('permissions_id_seq'::regclass),\n    name VARCHAR(100) NOT NULL,\n    description TEXT,\n    module VARCHAR(50),\n    created_at TIMESTAMPTZ DEFAULT now()\n);\n\n"
  },
  {
    "create_table_sql": "-- ================================================\n-- TABELA: product_entries\n-- ================================================\nDROP TABLE IF EXISTS public.product_entries CASCADE;\nCREATE TABLE public.product_entries (\n    id BIGINT NOT NULL DEFAULT nextval('product_entries_id_seq'::regclass),\n    product_id BIGINT NOT NULL,\n    invoice_number VARCHAR(50) NOT NULL,\n    invoice_series VARCHAR(10),\n    supplier_name VARCHAR(255),\n    supplier_cnpj VARCHAR(18),\n    batch_number VARCHAR(50),\n    manufacture_date DATE,\n    expiration_date DATE,\n    quantity NUMERIC(10, 2) NOT NULL,\n    unit_cost NUMERIC(10, 2) NOT NULL,\n    total_cost NUMERIC(10, 2) NOT NULL,\n    entry_date DATE DEFAULT CURRENT_DATE,\n    notes TEXT,\n    created_at TIMESTAMPTZ DEFAULT now(),\n    created_by UUID\n);\n\n"
  },
  {
    "create_table_sql": "-- ================================================\n-- TABELA: products\n-- ================================================\nDROP TABLE IF EXISTS public.products CASCADE;\nCREATE TABLE public.products (\n    id BIGINT NOT NULL DEFAULT nextval('products_id_seq'::regclass),\n    code VARCHAR(50),\n    name VARCHAR(255) NOT NULL,\n    description TEXT,\n    category VARCHAR(100),\n    unit VARCHAR(20) DEFAULT 'UN'::character varying,\n    price NUMERIC(10, 2) DEFAULT 0,\n    cost_price NUMERIC(10, 2) DEFAULT 0,\n    stock_quantity NUMERIC(10, 2) DEFAULT 0,\n    reserved_quantity NUMERIC(10, 2) DEFAULT 0,\n    min_stock NUMERIC(10, 2) DEFAULT 0,\n    max_stock NUMERIC(10, 2) DEFAULT 0,\n    location VARCHAR(100),\n    brand VARCHAR(100),\n    weight NUMERIC(10, 3),\n    is_active BOOLEAN DEFAULT true,\n    created_at TIMESTAMPTZ DEFAULT now(),\n    updated_at TIMESTAMPTZ DEFAULT now(),\n    created_by UUID,\n    updated_by UUID\n);\n\n"
  },
  {
    "create_table_sql": "-- ================================================\n-- TABELA: profiles\n-- ================================================\nDROP TABLE IF EXISTS public.profiles CASCADE;\nCREATE TABLE public.profiles (\n    id UUID NOT NULL,\n    email TEXT,\n    role TEXT DEFAULT 'operador'::text,\n    full_name TEXT,\n    avatar_url TEXT,\n    created_at TIMESTAMPTZ DEFAULT now(),\n    updated_at TIMESTAMPTZ DEFAULT now(),\n    phone TEXT,\n    document TEXT,\n    birth_date DATE,\n    address TEXT,\n    city TEXT,\n    state TEXT,\n    zip_code TEXT,\n    country TEXT DEFAULT 'Brasil'::text,\n    language TEXT DEFAULT 'pt-BR'::text,\n    timezone TEXT DEFAULT 'America/Sao_Paulo'::text,\n    notifications_enabled BOOLEAN DEFAULT true,\n    dark_mode BOOLEAN DEFAULT false,\n    last_login TIMESTAMPTZ,\n    login_count INTEGER DEFAULT 0,\n    metadata JSONB DEFAULT '{}'::jsonb,\n    display_name TEXT,\n    status VARCHAR(20) DEFAULT 'active'::character varying\n);\n\n"
  },
  {
    "create_table_sql": "-- ================================================\n-- TABELA: role_permissions\n-- ================================================\nDROP TABLE IF EXISTS public.role_permissions CASCADE;\nCREATE TABLE public.role_permissions (\n    id INTEGER NOT NULL DEFAULT nextval('role_permissions_id_seq'::regclass),\n    role_name VARCHAR(50) NOT NULL,\n    permission_id INTEGER,\n    created_at TIMESTAMPTZ DEFAULT now()\n);\n\n"
  },
  {
    "create_table_sql": "-- ================================================\n-- TABELA: sale_items\n-- ================================================\nDROP TABLE IF EXISTS public.sale_items CASCADE;\nCREATE TABLE public.sale_items (\n    id BIGINT NOT NULL DEFAULT nextval('sale_items_id_seq'::regclass),\n    sale_id BIGINT NOT NULL,\n    product_id BIGINT NOT NULL,\n    product_name VARCHAR(255) NOT NULL,\n    product_code VARCHAR(50),\n    quantity NUMERIC(10, 2) NOT NULL,\n    unit_price NUMERIC(10, 2) NOT NULL,\n    total_price NUMERIC(10, 2) NOT NULL,\n    created_at TIMESTAMPTZ DEFAULT now()\n);\n\n"
  },
  {
    "create_table_sql": "-- ================================================\n-- TABELA: sales\n-- ================================================\nDROP TABLE IF EXISTS public.sales CASCADE;\nCREATE TABLE public.sales (\n    id BIGINT NOT NULL DEFAULT nextval('sales_id_seq'::regclass),\n    sale_number VARCHAR(50) NOT NULL,\n    customer_id BIGINT,\n    customer_name VARCHAR(255),\n    customer_phone VARCHAR(20),\n    total_amount NUMERIC(10, 2) NOT NULL DEFAULT 0,\n    discount_amount NUMERIC(10, 2) DEFAULT 0,\n    discount_percent NUMERIC(5, 2) DEFAULT 0,\n    coupon_code VARCHAR(50),\n    final_amount NUMERIC(10, 2) NOT NULL DEFAULT 0,\n    payment_method VARCHAR(50) DEFAULT 'cash'::character varying,\n    payment_status VARCHAR(20) DEFAULT 'pending'::character varying,\n    status VARCHAR(20) DEFAULT 'completed'::character varying,\n    notes TEXT,\n    created_at TIMESTAMPTZ DEFAULT now(),\n    created_by UUID,\n    updated_at TIMESTAMPTZ DEFAULT now(),\n    cancelled_at TIMESTAMP,\n    cancelled_by UUID,\n    cancellation_reason TEXT,\n    cancellation_notes TEXT,\n    approved_by UUID\n);\n\n"
  },
  {
    "create_table_sql": "-- ================================================\n-- TABELA: stock_count_items\n-- ================================================\nDROP TABLE IF EXISTS public.stock_count_items CASCADE;\nCREATE TABLE public.stock_count_items (\n    id UUID NOT NULL DEFAULT gen_random_uuid(),\n    count_session_id UUID NOT NULL,\n    product_id BIGINT NOT NULL,\n    system_quantity NUMERIC(10, 2) NOT NULL DEFAULT 0,\n    system_cost NUMERIC(10, 2) DEFAULT 0,\n    counted_quantity NUMERIC(10, 2),\n    difference NUMERIC(10, 2),\n    status VARCHAR(50) NOT NULL DEFAULT 'pending'::character varying,\n    notes TEXT,\n    counted_by UUID,\n    counted_at TIMESTAMPTZ,\n    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),\n    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()\n);\n\n"
  },
  {
    "create_table_sql": "-- ================================================\n-- TABELA: stock_count_sessions\n-- ================================================\nDROP TABLE IF EXISTS public.stock_count_sessions CASCADE;\nCREATE TABLE public.stock_count_sessions (\n    id UUID NOT NULL DEFAULT gen_random_uuid(),\n    name VARCHAR(255) NOT NULL,\n    description TEXT,\n    location VARCHAR(255),\n    responsible VARCHAR(255) NOT NULL,\n    status VARCHAR(50) NOT NULL DEFAULT 'in_progress'::character varying,\n    created_by UUID,\n    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),\n    completed_at TIMESTAMPTZ,\n    completed_by UUID,\n    cancelled_at TIMESTAMPTZ,\n    cancelled_by UUID,\n    total_items INTEGER DEFAULT 0,\n    counted_items INTEGER DEFAULT 0,\n    diverged_items INTEGER DEFAULT 0,\n    adjustments JSONB DEFAULT '[]'::jsonb,\n    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),\n    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()\n);\n\n"
  },
  {
    "create_table_sql": "-- ================================================\n-- TABELA: stock_movements\n-- ================================================\nDROP TABLE IF EXISTS public.stock_movements CASCADE;\nCREATE TABLE public.stock_movements (\n    id BIGINT NOT NULL DEFAULT nextval('stock_movements_id_seq'::regclass),\n    product_id BIGINT NOT NULL,\n    movement_type VARCHAR(20) NOT NULL,\n    quantity NUMERIC(10, 2) NOT NULL,\n    quantity_before NUMERIC(10, 2) NOT NULL,\n    quantity_after NUMERIC(10, 2) NOT NULL,\n    reference_id UUID,\n    reference_type VARCHAR(50),\n    reason TEXT,\n    created_at TIMESTAMPTZ DEFAULT now(),\n    created_by UUID,\n    sale_id BIGINT\n);\n\n"
  },
  {
    "create_table_sql": "-- ================================================\n-- TABELA: system_logs\n-- ================================================\nDROP TABLE IF EXISTS public.system_logs CASCADE;\nCREATE TABLE public.system_logs (\n    id UUID NOT NULL DEFAULT gen_random_uuid(),\n    user_id UUID,\n    user_email TEXT,\n    user_role TEXT,\n    action TEXT NOT NULL,\n    entity_type TEXT,\n    entity_id TEXT,\n    old_data JSONB,\n    new_data JSONB,\n    ip_address TEXT,\n    user_agent TEXT,\n    details JSONB,\n    created_at TIMESTAMPTZ DEFAULT now()\n);\n\n"
  },
  {
    "create_table_sql": "-- ================================================\n-- TABELA: system_settings\n-- ================================================\nDROP TABLE IF EXISTS public.system_settings CASCADE;\nCREATE TABLE public.system_settings (\n    id UUID NOT NULL DEFAULT gen_random_uuid(),\n    currency VARCHAR(3) DEFAULT 'BRL'::character varying,\n    date_format VARCHAR(20) DEFAULT 'DD/MM/YYYY'::character varying,\n    time_format VARCHAR(10) DEFAULT '24h'::character varying,\n    language VARCHAR(10) DEFAULT 'pt-BR'::character varying,\n    timezone VARCHAR(50) DEFAULT 'America/Sao_Paulo'::character varying,\n    updated_at TIMESTAMPTZ DEFAULT now()\n);\n\n"
  }
]